#!/bin/bash
#
# Usage
# -----
#
# By default this will build the debug release
mkdir -p release
node_modules/browserify/bin/cmd.js main.jsx \
    -t [babelify --sourceMapRelative .] \
    --outfile release/bundle.js \
    --debug
